services:
  postgres :
    image: postgres
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
  pgdata:



